### ISSUE TITLE
Setting ScalaPB's `flatPackage` to true causes compilation of generated Scala source to fail

### ISSUE THREAD

**Issue by vyshane** [btlines/grpcmonix#3]
Setting ScalaPB's `flatPackage` to true causes compilation of generated Scala source to fail:

```
PB.targets in Compile := Seq(
  scalapb.gen(grpc = true, flatPackage = true) -> (sourceManaged in Compile).value,
  grpcmonix.generators.GrpcMonixGenerator -> (sourceManaged in Compile).value
)
```

Sample error:

```
[error] /Users/shane/node/app/target/scala-2.12/src_managed/main/mu/node/api/user/UserGrpcMonix.scala:19: object SignUpRequest is not a member of package mu.node.user
[error]       new Marshaller(mu.node.user.SignUpRequest),
[error]                                            ^
```

This while compiling a file called `user.proto`.

**Comment by btlines** [comment]
Thanks for reporting this issue. 
That's correct that there is currently no way to pass the `flatPackage` option in the `build.sbt`
The only way is to add this option in the .proto file itself.

**Comment by btlines** [comment]
Solved via https://github.com/btlines/grpcmonix/pull/4
