### ISSUE TITLE
bindService should pass ServiceDescriptor to ServerServiceDefinition.builder

### ISSUE THREAD

**Issue by jriecken** [btlines/grpcmonix#8]
The current generated code for `bindService` calls:

```scala
ServerServiceDefinition
  .builder("the.name.of.the.Service")
  ...
```

While this works, it doesn't register the service in a way that the `ProtoReflectionService` can see.

The generated code already has a ServiceDescriptor that properly describes the service:

```scala
val SERVICE: _root_.io.grpc.ServiceDescriptor = ...
```

If `bindService` is changed to call this instead, reflection works:

```scala
ServerServiceDefinition
  .builder(SERVICE)
  ...
```

**Comment by btlines** [comment]
Solved via https://github.com/btlines/grpcmonix/pull/9

**Comment by jriecken** [comment]
Thank you!
